"""fix created at

Revision ID: 2ec06dd0417e
Revises: 1b142c5cda17
Create Date: 2026-02-13 13:58:18.691072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec06dd0417e'
down_revision: Union[str, Sequence[str], None] = '1b142c5cda17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('reviews', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
